server:
  port: 8080

spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #druid
      url: jdbc:mysql://localhost:3306/nj-2203-project?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 111111
      username: root

    # thymeleaf config
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

  # redis config
  redis:
    password: 123456
    host: 118.178.179.109
    port: 6379
    timeout: 2000
    database: 1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoyao.entity.po
