server:
  port: 8081

spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #druid
      url: jdbc:mysql://localhost:3306/nj-2203-project?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      password: 111111
      username: root
  main:
    allow-bean-definition-overriding: true
    #表示后发现的bean会覆盖之前相同名称的bean。

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoyao.entity.po

